### ISSUE TITLE
Environment deployment notifications are gone

### ISSUE THREAD

**Issue by iorlas** [integrations/slack#1152]
*The gh bot keeps saying "see the contribution guidelines", but it leads to the 404 page "https://github.com/integrations/slack/blob/master/CONTRIBUTING.md#getting-started", so yeah, going commando here.*

Previous integration has two important features:

- Deploy command, which implements basic ChatOps flow to initiate deployment on any environment
- Notifications when one environment or another receives events about deployment status. It were really nice and sexy, especially considering the fact it did reuse existing notification record to update the status, really nice

So, basically, everything related to the *environments* and *delivery/CD/deployment* is **gone**.

Recently GH has released an option to control [the environment protection rules](https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/) (including approvals), but it is available only for the public repos and enterprise offering. So it is not available for the private repos, even in paid team accounts.

Considering the last issue, I envision GitHub is considering moving all the delivery-related features into the "public or enterprise" section. The fact the new slack integration has all delivery-related features **removed**, I suspect my envision is correct.

So, what is the status of the delivery-related features in slack integration?

**Comment by ashokirla** [comment]
@iorlas We apologize for the inconvenience. We are taking a relook at the deploy functionality as the current experience is limited and doesn't address all the scenarios and we see very little adoption. We have removed deploy command support as part of the new version. We will evaluate the feedback and then build a holistic experience that customers need.

It would be great if you can share your scenarios/requirements around deploy.

Also, can you point to the location where you are seeing the mention by GitHub bot about contribution.

**Comment by iorlas** [comment]
> Also, can you point to the location where you are seeing the mention by GitHub bot about contribution.

> Thanks for opening this issue! If you would like to help implement an improvement, [read more about contributing](https://github.com/integrations/slack/blob/master/CONTRIBUTING.md#getting-started) and consider submitting a pull request.

Here :)

**Comment by olly** [comment]
We recently integrated our deployment process (which is run on GitHub Actions) with GitHub's Deployment APIs, precisely so we could have easy notifications of deployments in Slack. We would appreciate it if we could keep those notifications.

**Comment by cmark** [comment]
Same issue here. We are not using `/github deploy` functionality but the environments part from the PRs are missing. This is a serious non-backward compatible change that can affect teams who are using GitHub Actions to build/deploy their products. 

I understand the issues you are having with the current solution and we were not a fan of the `deploy` command either, but we (and many others probably) would really appreciate to get back the original notification content with the deployment locations/link/etc.

**Comment by billputer** [comment]
We're also heavy users of deploy notifications, and I was very disappointed to see GitHub trying to silently drop this functionality. We'll be downgrading to the old version of the app until this is fixed.

**Comment by sauln** [comment]
We also heavily used the deployment notifications. We did not use `/github deploy` at all, but the deployment markers were very important to us.  

Additionally, the documentation for the app says that deployment notifications are still around: https://slack.com/help/articles/232289568-GitHub-for-Slack#github-for-slack-1.

We would not have upgraded if we knew this important feature was missing.

![Screen Shot 2021-04-15 at 6 13 15 PM](https://user-images.githubusercontent.com/5808961/114957655-548e1980-9e16-11eb-9cd9-32177d47f549.png)

**Comment by bendavies** [comment]
we were also subscribing to deployment status, which are now sorely missed!

**Comment by cy6erskunk** [comment]
We were also heavy users of the deployment notifications, it is really disturbing that such a change comes completely out of the blue 😿

**Comment by tonydehnke** [comment]
@iorlas We used it to get notifications of builds on Heroku - success, fails, etc.  It was convenient as if something went wrong; we knew about it in Slack right away.  Also, if doing a build in a Review App or Staging that we wanted to test, we were alerted once the deployment was successful so we could test it, etc.  

Here is a sample of what we used to see from Github Legacy:

![image](https://user-images.githubusercontent.com/36720180/114995162-bbb7d680-9ec7-11eb-9bf4-a4c49e27a67e.png)

**Comment by evan10s** [comment]
We also greatly miss the deployment notifications.  Both the modal to initiate deployments and especially the deployment notifications were extremely helpful to us.  I could live without being able to trigger deployments from the bot, but it'd be great to have deployment status notifications back since deployments show in the web UI.

**Comment by d-vine** [comment]
Same here. We rolled our own build and deployment system on top of Github actions and CloudFormation that automatically  deploys code and infrastructure updates to various environments. All our teams communication happens in slack, so it was very helpful to see the state of ongoing deployments there. Please reconsider!

![image](https://user-images.githubusercontent.com/996197/115598166-1a09fe00-a2a8-11eb-8f41-997d74072260.png)

**Comment by robdaemon** [comment]
> We are not using `/github deploy` functionality but the environments part from the PR notifications are missing.

Same here, we use the notification part and I've been trying to figure out for several days why it stopped working.

**Comment by ashokirla** [comment]
Based on the customer feedback, we have decided to bring back deployment notifications functionality to the new slack app. This should be available very soon.

**Comment by OleMchls** [comment]
While we all wait, we've build a custom version using GitHub Actions:

```yaml
name: Deployment Status Notifications

on: deployment_status

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: "https://hooks.slack.com/services/XXXXX/XXXXX"
      SLACK_ICON: "https://avatars.githubusercontent.com/u/XXXXX"
      SLACK_TITLE: GitHub Deployment
      SLACK_USERNAME: Steve McBots @ GitHub
      DEPLOYMENT_STATE: ${{ github.event.deployment_status.state }}
      DEPLOYMENT_ENV: ${{ github.event.deployment.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Set the pending message
        if: github.event.deployment_status.state == 'pending'
        run: |
            echo "SLACK_MESSAGE=Deployment ${DEPLOYMENT_STATE} :hourglass: in ${DEPLOYMENT_ENV}" >> $GITHUB_ENV
            echo "SLACK_COLOR=warning" >> $GITHUB_ENV
      - name: Set the success message
        if: github.event.deployment_status.state == 'success'
        run: |
            echo "SLACK_MESSAGE=Deployment ${DEPLOYMENT_STATE} :rocket: in ${DEPLOYMENT_ENV}" >> $GITHUB_ENV
            echo "SLACK_COLOR=good" >> $GITHUB_ENV
      - name: Set the error message
        if: github.event.deployment_status.state == 'failure' || github.event.deployment_status.state == 'error'
        run: |
            echo "SLACK_MESSAGE=Deployment ${DEPLOYMENT_STATE} :sadpanda: in ${DEPLOYMENT_ENV}" >> $GITHUB_ENV
            echo "SLACK_COLOR=danger" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
```

Just in case anyone of you might also find this useful :)
