### ISSUE TITLE
Deployment Reviews Not Working

### ISSUE THREAD

**Issue by AngellusMortis** [integrations/slack#1364]
**Describe the bug**
Deployment Review Requests (seen below) do not seem to be working for our Slack. 
![image](https://user-images.githubusercontent.com/490848/155222119-459157bf-efb6-4f5b-a7b6-9ca2fd29e899.png)

We got the deployment review request once in our Slack last week which is how I learned about their existence. I have not been able to get them to work again since though.

**To Reproduce**
1. Create an environment that requires someone to approve the review.
2. Make a workflow using that deploy:
```yaml
...
jobs:
  ...
  deploy:
    name: Deploy to Staging
    environment:
      name: ENVIRONMENT_FROM_1
      url: https://staging.example.com
```

**Expected behavior**

Expect to see message similar to: 
![image](https://user-images.githubusercontent.com/490848/155222119-459157bf-efb6-4f5b-a7b6-9ca2fd29e899.png)

**Additional context**

The deploys are firing from self-hosted runners if that makes a difference.

Unfortunately, the project and the code are not open source so I cannot really provide a lot more details here. We do have an Enterprise account and we even have a shared Slack between Github and our company (Multi Media) if you would like to message me to troubleshoot.
