### ISSUE TITLE
GHA and slack by October 2022? Any updates?

### ISSUE THREAD

**Issue by zomgbre** [integrations/slack#1489]
Hi there! 

We absolutely love the slack integration and the work you have all done.  :) 

My team and I are anxiously awaiting updates to this official slack + github integration so that we can setup more robust alerting for when non-deployment steps / re-usable workflows fail through the existing slack github app. 

I see that there is this in the repo README:
> GitHub Actions notifications and manage capabilities - Provide capabilities to run, view and manage workflows from chat. We are aiming to rollout this support by October 2022.

Any updates on this? I've checked the Github Public Roadmap but there is nothing there that I could find on slack.

There are other slack actions out there that can be used to do this, however it's not very pretty and leaves the workflow file pretty cluttered. _**(If anyone has examples of a non-cluttered workflow configuration using one of the other slack integrations I'd be ecstatic).**_ 

I attempted to make the actions less verbose by putting it in a re-usable workflow, but then the re-usable workflow shows up as part of our pipeline and I don't want that confusing people (unfortunately it happens...:facepalm:).

**Comment by js-beaulieu** [comment]
@zomgbre The way we do it at work for now is a `workflow_run` action.

```yaml
name: Workflow status notifications
run-name: Notify status for workflow ${{ github.event.workflow_run.name }}

on:
  workflow_run:
    workflows: [CI checks]
    types: [completed]
    branches: [develop]

jobs:
  notify-slack:
    name: Send workflow status to Slack
    runs-on: ubuntu-22.04
    steps:
      - name: Send payload to Slack Custom Workflow webhook
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "updated_at": "${{ github.event.workflow_run.updated_at }}",
              "branch": "${{ github.event.workflow_run.head_branch }}",
              "commit": "${{ github.event.workflow_run.head_sha }}",
              "name": "${{ github.event.workflow_run.name }}",
              "status": "${{ github.event.workflow_run.conclusion == 'success' && '🟢' || '🔴' }} ${{ github.event.workflow_run.conclusion }}",
              "url": "${{ github.event.workflow_run.html_url }}",
              "number": "${{ github.event.workflow_run.run_number }}",
              "attempt": "${{ github.event.workflow_run.run_attempt }}",
              "repo_name": "${{ github.event.repository.full_name }}",
              "sender_name": "${{ github.event.sender.login }}"
            }
```

Then post a message through Workflow Builder.

Can't wait for first-party integration though, as this is proving to be rather tedious to manage (adding new fields entails opening a PR for the workflow, then changing the Slack message through Workflow Builder), and limited by Workflow Builder's capabilities (e.g. unable to create links based on variables)
