### ISSUE TITLE
Notify workflows only on errors

### ISSUE THREAD

**Issue by samsaggace** [integrations/slack#1563]
**Is your feature request related to a problem? Please describe.**
To avoid generating too much noise on our slack channel, I would like to get a notification on workflows only when it fails.

**Describe the solution you'd like**
Adding this configuration like `workflows:{event:"push", branch:"main", when: "failed" }` would be super useful.

**Describe alternatives you've considered**
For the moment we are using a github action (ravsamhq/notify-slack-action) to do the job but it has to be added on every job of every workflow...

**Additional context**
To be clear, having only this notification on workflows would be perfect for me :
<img width="310" alt="image" src="https://user-images.githubusercontent.com/12609676/206412836-b8fdd489-cefd-47e5-bf64-91cc2cda28f1.png">
without in progress and in thread details

Thanks !

**Comment by ashokirla** [comment]
Thanks for the feedback. We will collate all the requests and pick it up during the next iteration of improvements.

**Comment by a-pedroso** [comment]
This feature would be super useful.
thumbs up!

**Comment by danielsiwiec** [comment]
+1 🙏

**Comment by Yarden-zamir** [comment]
Is there any update on this? This would be very useful

**Comment by surajthapa12** [comment]
@ashokirla 
> Thanks for the feedback. We will collate all the requests and pick it up during the next iteration of improvements.

Do we know when the next iteration of improvements will be released?

**Comment by pashcan** [comment]
The ability to subscribe to only the failed workflows would be super helpful to help reduce the notification noise :pray:

**Comment by mknet3** [comment]
any update here? 🙏 It would be awesome to avoid including many extra steps in all the workflows just for notifications

**Comment by connorjchen** [comment]
Would be super helpful

**Comment by MerzDaniel** [comment]
Waiting desperately for this. Otherwise notifications for many repositories are too spammy

**Comment by MerzDaniel** [comment]
Jenkins has the nice feature for notifying on 
- failed builds
- fixed builds (first successful build after a fail)

So extending the config as in the main description could be something like this: 
`workflows:{event:"push", branch:"main", when: "failed,fixed" }`

**Comment by rohammosalli** [comment]
you can improve GitHub Actions workflow configuration to make notifications more efficient. I propose implementing a configuration such as: `workflows:{event:"pull_request","push", "schedule",  when: "failed"}`

This configuration ensures that we receive notifications only when a workflow has failed, making it easier to focus on issues that need immediate attention. Once the failed workflow is resolved and we receive a green notification

**Comment by Shekhar-rv** [comment]
+1

**Comment by NegatioN** [comment]
+1 Not having this makes this otherwise perfect integration almost unusable in our case.
It would be great to hear an update on when we could expect someone to start work on this :pray:

**Comment by fivestar** [comment]
+1

**Comment by rohammosalli** [comment]
I created a custom GitHub Action for this feel free to use it which handles these conditions, it checks all jobs if any job failed you don't need to check inside your workflow

- Send a success message if the last build failed but the current build was successful.
- or don't sends notifications for successful workflow runs if you set `SEND_SUCCESS_NOTIFICATIONS` environment variable to false.

You can check it out here
https://github.com/rohammosalli/slack-action

**Comment by rohammosalli** [comment]
I created a custom Github action that supports these conditions. it also checks all failed jobs no need anything to add inside the workflow file, you can add it as a separate job to your workflow. 

- Send a success message if the last build failed but the current build was successful.
- or don’t sends notifications for successful workflow runs if you set `SEND_SUCCESS_NOTIFICATIONS` environment variable to false.|
- Send a message if there was a failed build.

You can check it here: https://github.com/rohammosalli/slack-action

**Comment by yoannteruel** [comment]
+1

**Comment by TakeshiDaveau** [comment]
+1

**Comment by xnog** [comment]
+1

**Comment by kendra-human** [comment]
+1

**Comment by danlester** [comment]
Before any updates are released on the official GitHub app, anyone wanting more flexibility over workflow notifications can try Endid (free for open-source repos).

You can choose to be notified of any or all statuses (queued, success, failure, canceled), and optionally choose to be notified only when the state changes - when a workflow that was previously successful suddenly fails, and then once it is fixed again.

This offers drastically reduced noise for a lot of organizations, compared to the official integration! Hope it helps some of you here for now.

The [Endid Slack app](https://endid.slack.com/apps/A01F9F1F0JZ-endid-for-github) is linked here.

**Comment by gabestep-emp** [comment]
Hi all - This is my checker so I don't need to add it to every job.
```
name: Check for master or prod failure
on:
  workflow_run:
    workflows: [Build and Test, Build and Test 2]
    types: [completed]
    branches: [main,prod]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    steps:
      - uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          notification_title: " ${{github.event.workflow_run.name}} - ${{github.event.workflow_run.conclusion}} on ${{github.event.workflow_run.head_branch}} - <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
          message_format: ":fire: *${{github.event.workflow_run.name}}* ${{github.event.workflow_run.conclusion}} in <${{github.server_url}}/${{github.repository}}/${{github.event.workflow_run.head_branch}}|${{github.repository}}>"
          footer: "Linked Repo <${{github.server_url}}/${{github.repository}}|${{github.repository}}> | <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MASTER_PROD_FAIL_SLACK }}
```
![image](https://github.com/integrations/slack/assets/132367552/f3bf53ae-f695-42e7-96bb-2303bf70df89)
@samsaggace

**Comment by Shashwat-SRE** [comment]
@ashokirla  any update on when this will be implemented ?

**Comment by sammorrisdesign** [comment]
+1 to this. Would be very useful for us to only know about the errors without having to modify our workflow file across multiple repos.

**Comment by realkosty** [comment]
for god's sake please.

**Comment by sergekukharev** [comment]
Shame I have to install custom action and deal with Slack hooks. Does anyone at GitHub still maintain this integration?

**Comment by nadasaiyed** [comment]
has there been any progress on this? This would be a very useful feature.

**Comment by aiell0** [comment]
+1 to wanting this feature. I am getting around this with slack notifications but would love to get rid of that.

**Comment by emreabanozoglu** [comment]
+1

**Comment by ohadasulin1** [comment]
+1 
Just out of curiosity, why would anyone want to subscribe to all events if everything works as it should?
I mean, if the output is meant for human consumption on a slack channel :)

**Comment by illegalnumbers** [comment]
how is this still not an option?

**Comment by Seung-o** [comment]
Hello. I would prefer not to receive notifications for canceled GitHub actions. It would be appreciated if there could be an update on the progress of this discussion and, if resolved, an update in the README.md would be beneficial.

**Comment by mayconamaroCW** [comment]
+1 I'd love this

**Comment by illegalnumbers** [comment]
Is this still not available 2 years later?

**Comment by mayankpande88** [comment]
any progress on this? This would be a very useful feature.

**Comment by Seselian** [comment]
Any update on this? 🤔

**Comment by rfsmart-lhunter** [comment]
Please add this feature! It has been over a year since the original request and there's obviously a LOT of people wanting/needing it!

**Comment by fimasultana** [comment]
Is there an update for failed job alerts integration in Slack only?

**Comment by vrumiantsev** [comment]
+1 This feature would be super helpful in order to reduce channel noise

**Comment by danlester** [comment]
![Screenshot 2024-04-03 at 14 44 46](https://github.com/integrations/slack/assets/786238/dc6219c3-4b44-48d5-9c37-e2ef9f271b90)

A friendly reminder that [Endid](https://endid.app/) offers enhanced customization (it can even notify only on first failure, and/or first fix). It's free for public repos.

**Comment by AMMARESIDENTE** [comment]
***@***.******@***.*** SULFIKAR SETIAWAN PASAURI

Yahoo Mail: Cari, Atur, Taklukkan 
 
  Pada Jum, 23 Feb 2024 pada 10:06, ***@***.***> menulis:   


Any update on this? 🤔

**Comment by haizaar** [comment]
Is GitHub becoming one of those products that take forever to deliver simple usability improvements?

**Comment by szymanka** [comment]
![0_PUSS-IN-BOOTS](https://github.com/integrations/slack/assets/123408368/20b3b4f0-1eec-452e-8e9e-7aeeb82e54a7)

**Comment by josh-hong-pps** [comment]
+1

**Comment by aa-mikemonaghan** [comment]
+1, I'm surprised this is a limitation of the platform in 2024. 

Having to resort to Slack webhooks and third-party/internal Actions to get this functionality is pretty silly.

**Comment by AMMARESIDENTE** [comment]
mx#1707

Pada Sab, 8 Jun 2024 04:55, aa-mikemonaghan ***@***.***>
menulis:

**Comment by illegalnumbers** [comment]
Any update on this?

**Comment by kuronekomichael** [comment]
I eagerly anticipating the resolution of this issue 😢

**Comment by PramodKumarYadav** [comment]
The person assigned to this issue has not added any commit in this year so most probably he is not working there any more. Its a pity that even after so many votes the issue doesn't have any priority. Makes the noisy official integration useless :/

**Comment by OmarTawfik** [comment]
Seems like they added workflow notification filters, which support `name`, `event`, `actor`, and `branch` filters:
https://github.com/integrations/slack?tab=readme-ov-file#workflow-notification-filters

The one filter that is missing (and I believe is actually the most important filter of all) is `conclusion`, so that people can filter by `event.workflow_run.conclusion`, which is either `success` or `failure`:
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow

I suspect it is now much easier/cheaper to implement this feature, which is immensely helpful to anyone working on large codebases.

**Comment by ichbinjon** [comment]
+1 to this, would be super useful

**Comment by zendesk-johnhenry** [comment]
+1

**Comment by cquaresma** [comment]
+1 let us eat cake.

**Comment by Tom-Hudson** [comment]
+1

**Comment by davidhazell-tst** [comment]
+1

**Comment by lufia** [comment]
+1

**Comment by tailaiw** [comment]
> Seems like they added workflow notification filters, which support `name`, `event`, `actor`, and `branch` filters: https://github.com/integrations/slack?tab=readme-ov-file#workflow-notification-filters
> 
> The one filter that is missing (and I believe is actually the most important filter of all) is `conclusion`, so that people can filter by `event.workflow_run.conclusion`, which is either `success` or `failure`: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
> 
> I suspect it is now much easier/cheaper to implement this feature, which is immensely helpful to anyone working on large codebases.

I'm not optimistic about this because the `event` is something known on trigger, while the `conclusion` is something known on the end of the workflow. I hope I'm wrong because obviously this is a much needed feature.

**Comment by tuliolima** [comment]
+1

**Comment by alberto-corrales** [comment]
it would be amazing to have these filters available to prevent generating noise in our channels. It is true we can also do it with webhooks, but it would be nice if we could leverage the Github app

**Comment by na-jakobs** [comment]
This is a much needed feature.

**Comment by preston-wagner** [comment]
@snankani is ashokirla no longer working for github? Could this possibly be assigned to someone else?

**Comment by innomatics** [comment]
Building on the workaround from @gs-emp - if you want to avoid setting up a webhook, you can subscribe the bot to a simple workflow that always fails, and dispatch that by GitHub API when your important workflows fail.  

Note that using `worflow_call` didin't work, because that only executes the steps in the re-used workflow, without actually running it.

.github/workflows/failure.ml:
```
name: Failure
on:
  workflow_dispatch:

jobs:
  failure-reporting-job:
    runs-on: ubuntu-latest
    steps:
      # Do nothing, unsuccessfully
      - run: false 
```

.github/workflows/completion.xml
```
name: Completion
on:
  workflow_run:
    workflows:
      - My Important Workflow 
    types:
      - completed

jobs:
  on-failure:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_failure
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/failure.yml/dispatches
          ref: 'main'
          inputs: '{}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
