### ISSUE TITLE
Labels added after PR creation do not trigger Slack messages

### ISSUE THREAD

**Issue by gergelyke-dd** [integrations/slack#1594]
**Describe the bug**
Once an PR is created, labels added to it do not trigger Slack notifications

**To Reproduce**
1. Subscribe to pull using a label as a filter
2. Create a PR
3. Once the PR is open, add the label you created the filter for
4. No Slack message is triggered

**Expected behavior**
Slack message is triggered

**Comment by gergelyke-dd** [comment]
@sanjeev9160 any chance there's a workaround here for the use-case outlined above?

We'd like to use tags to signal different life-cycle events of a PR, and for that we'd like to use Slack notifications

**Comment by gileswells** [comment]
@sanjeev9160 would it be appropriate to make a feature request that there be a new trigger added to this integration that fires based on when a label is added or removed from a PR / issue?

My proposed use case:
When using the [stale](https://github.com/actions/stale) GitHub Action we want to be able to add the `stale` label and then have this GitHub integration pick up on that and send an update to the channel the subscription is in. Basically we'd like to have this command function at any point during a PR's lifecycle.

`/github subscribe [repo] labeled:{name: "label name", event: "[added|removed|both]", type: "[issue|pull|both]"}`
defaults would, i'd assume, be both for event and type properties.

If desired I can make this it's own issue ticket.

**Comment by sanjeev9160** [comment]
@gergelyke-dd @gileswells I have added it as a Feature request into the backlog. Thanks.

**Comment by dannysauer** [comment]
FWIW: this also breaks anyone using an autolabel github action, since those labels need the PR to be opened before the action can run.  If there's a better way to make labels appear in the PR based on changed files before the PR is opened, I'm all ears.

**Comment by dannysauer** [comment]
Perhaps relevant: the alert does come through when a labeled PR is closed.  Upon close of a PR with a filtered label which wasn't present at opening, the "new PR" message gets created, and the close comment gets posted as a reply which is CC'd to the channel as normal.  So it seems there is logic hidden away somewhere which can create the top level post upon later filter-matching events. ;)

**Comment by benebene84** [comment]
Currently we manage this with a Slack workflow: 

```
name: Send Slack Notifications

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "pr_name": "${{ github.event.pull_request.title }}",
              "pr_link": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

But it would be great if this would work with the Github App in slack as well, then we could ditch this workflow.
