### ISSUE TITLE
/github deploy [repo] - task doesn't work 

### ISSUE THREAD

**Issue by rntdrts** [integrations/slack#968]
I have been using this integration and I want to thank you all for the great job you have done here! 👏 

I have been migrating some repositories into a monorepo. I'm using github actions to deploy each project. However, I thought I could separate each deploy by using the input `task` which is not working.

<img width="510" alt="Screenshot 2019-12-02 at 15 52 06" src="https://user-images.githubusercontent.com/3099777/69973619-b698f800-151b-11ea-825f-839530b38db5.png">

Is that even possible or am I not understanding properly what is the `task` input attribute related to?

Once again, Thanks!

**Comment by rntdrts** [comment]
After looking at the base code and dig up into github actions I was able to find the solution. 
In case anyone has the same problem, you can filter your jobs/steps by adding an `if`, like this:

```
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.deployment.task == 'name_of_task'
```
